
package frc.robot.ChoreoFiles;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;


/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj C_Climb = new ChoreoTraj(
	    "C_Climb",
	    OptionalInt.empty(),
	    2.01053,
	    new Pose2d(3.575, 3.75, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.7, 3.3, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj D_BumpAllianceNeutral = new ChoreoTraj(
	    "D_BumpAllianceNeutral",
	    OptionalInt.empty(),
	    1.11273,
	    new Pose2d(3.2, 5.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(5.7, 5.9, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_BumpNeutralAlliance = new ChoreoTraj(
	    "D_BumpNeutralAlliance",
	    OptionalInt.empty(),
	    1.28941,
	    new Pose2d(6.1, 5.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(3.2, 5.9, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_BUMP_D_Intake_45 = new ChoreoTraj(
	    "D_BUMP_D_Intake_45",
	    OptionalInt.empty(),
	    0.75639,
	    new Pose2d(6.1, 5.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(7.4, 6.5, Rotation2d.fromRadians(-0.785))
	);
	public static final ChoreoTraj D_Depot_D_BUMP = new ChoreoTraj(
	    "D_Depot_D_BUMP",
	    OptionalInt.empty(),
	    0.76895,
	    new Pose2d(1.1, 5.97, Rotation2d.fromRadians(3.142)),
	    new Pose2d(3.2, 5.9, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_Full_1Pass = new ChoreoTraj(
	    "D_Full_1Pass",
	    OptionalInt.empty(),
	    8.34462,
	    new Pose2d(3.6, 5.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(1.559, 3.437, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj D_Full_1Pass$0 = new ChoreoTraj(
	    "D_Full_1Pass",
	    OptionalInt.of(0),
	    1.88683,
	    new Pose2d(3.6, 5.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(6.1, 5.9, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_Full_1Pass$1 = new ChoreoTraj(
	    "D_Full_1Pass",
	    OptionalInt.of(1),
	    2.32449,
	    new Pose2d(6.1, 5.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(6.1, 2.5, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_Full_1Pass$2 = new ChoreoTraj(
	    "D_Full_1Pass",
	    OptionalInt.of(2),
	    1.45181,
	    new Pose2d(6.1, 2.5, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(3.2, 2.5, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_Full_1Pass$3 = new ChoreoTraj(
	    "D_Full_1Pass",
	    OptionalInt.of(3),
	    0.9876500000000004,
	    new Pose2d(3.2, 2.5, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(1.509, 0.621, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj D_Full_1Pass$4 = new ChoreoTraj(
	    "D_Full_1Pass",
	    OptionalInt.of(4),
	    1.6938400000000007,
	    new Pose2d(1.509, 0.621, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.559, 3.437, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj D_Intake_45_D_BUMP = new ChoreoTraj(
	    "D_Intake_45_D_BUMP",
	    OptionalInt.empty(),
	    1.62387,
	    new Pose2d(7.4, 6.5, Rotation2d.fromRadians(-0.785)),
	    new Pose2d(6.1, 5.9, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_Intake_45_H_BUMP = new ChoreoTraj(
	    "D_Intake_45_H_BUMP",
	    OptionalInt.empty(),
	    1.88785,
	    new Pose2d(7.4, 6.5, Rotation2d.fromRadians(-0.785)),
	    new Pose2d(6.1, 2.5, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj D_Partial_1Pass = new ChoreoTraj(
	    "D_Partial_1Pass",
	    OptionalInt.empty(),
	    11.45842,
	    new Pose2d(3.455, 5.655, Rotation2d.fromRadians(-0.785)),
	    new Pose2d(0.647, 7.612, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj D_Partial_1Pass$0 = new ChoreoTraj(
	    "D_Partial_1Pass",
	    OptionalInt.of(0),
	    2.06931,
	    new Pose2d(3.455, 5.655, Rotation2d.fromRadians(-0.785)),
	    new Pose2d(7.128, 7.325, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_Partial_1Pass$1 = new ChoreoTraj(
	    "D_Partial_1Pass",
	    OptionalInt.of(1),
	    3.52152,
	    new Pose2d(7.128, 7.325, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(6.411, 5.418, Rotation2d.fromRadians(2.356))
	);
	public static final ChoreoTraj D_Partial_1Pass$2 = new ChoreoTraj(
	    "D_Partial_1Pass",
	    OptionalInt.of(2),
	    1.5103299999999997,
	    new Pose2d(6.411, 5.418, Rotation2d.fromRadians(2.356)),
	    new Pose2d(2.915, 5.418, Rotation2d.fromRadians(2.356))
	);
	public static final ChoreoTraj D_Partial_1Pass$3 = new ChoreoTraj(
	    "D_Partial_1Pass",
	    OptionalInt.of(3),
	    0.4217500000000003,
	    new Pose2d(2.915, 5.418, Rotation2d.fromRadians(2.356)),
	    new Pose2d(2.54, 5.415, Rotation2d.fromRadians(2.356))
	);
	public static final ChoreoTraj D_Partial_1Pass$4 = new ChoreoTraj(
	    "D_Partial_1Pass",
	    OptionalInt.of(4),
	    3.93551,
	    new Pose2d(2.54, 5.415, Rotation2d.fromRadians(2.356)),
	    new Pose2d(0.647, 7.612, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj D_Start_D_BUMP = new ChoreoTraj(
	    "D_Start_D_BUMP",
	    OptionalInt.empty(),
	    0.35524,
	    new Pose2d(3.6, 5.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(3.2, 5.9, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj D_Start_D_Depot = new ChoreoTraj(
	    "D_Start_D_Depot",
	    OptionalInt.empty(),
	    0.99343,
	    new Pose2d(3.6, 5.9, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(1.1, 5.97, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_BumpNeutralAlliance = new ChoreoTraj(
	    "H_BumpNeutralAlliance",
	    OptionalInt.empty(),
	    1.28919,
	    new Pose2d(6.1, 2.5, Rotation2d.fromRadians(1.571)),
	    new Pose2d(3.2, 2.5, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_BUMP_H_Intake_45 = new ChoreoTraj(
	    "H_BUMP_H_Intake_45",
	    OptionalInt.empty(),
	    0.76904,
	    new Pose2d(6.1, 2.5, Rotation2d.fromRadians(1.571)),
	    new Pose2d(7.4, 1.627, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj H_Full_1Pass = new ChoreoTraj(
	    "H_Full_1Pass",
	    OptionalInt.empty(),
	    7.55263,
	    new Pose2d(3.6, 2.05, Rotation2d.fromRadians(1.571)),
	    new Pose2d(1.559, 4.488, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj H_Full_1Pass$0 = new ChoreoTraj(
	    "H_Full_1Pass",
	    OptionalInt.of(0),
	    1.73618,
	    new Pose2d(3.6, 2.05, Rotation2d.fromRadians(1.571)),
	    new Pose2d(6.1, 2.05, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Full_1Pass$1 = new ChoreoTraj(
	    "H_Full_1Pass",
	    OptionalInt.of(1),
	    2.4009099999999997,
	    new Pose2d(6.1, 2.05, Rotation2d.fromRadians(1.571)),
	    new Pose2d(5.974, 5.809, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Full_1Pass$2 = new ChoreoTraj(
	    "H_Full_1Pass",
	    OptionalInt.of(2),
	    1.3466300000000002,
	    new Pose2d(5.974, 5.809, Rotation2d.fromRadians(1.571)),
	    new Pose2d(3.283, 5.809, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Full_1Pass$3 = new ChoreoTraj(
	    "H_Full_1Pass",
	    OptionalInt.of(3),
	    0.8346900000000002,
	    new Pose2d(3.283, 5.809, Rotation2d.fromRadians(1.571)),
	    new Pose2d(1.181, 5.948, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Full_1Pass$4 = new ChoreoTraj(
	    "H_Full_1Pass",
	    OptionalInt.of(4),
	    1.2342199999999997,
	    new Pose2d(1.181, 5.948, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.559, 4.488, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj H_HumanPlayer_H_BUMP = new ChoreoTraj(
	    "H_HumanPlayer_H_BUMP",
	    OptionalInt.empty(),
	    0.80295,
	    new Pose2d(1.5, 0.65, Rotation2d.fromRadians(3.142)),
	    new Pose2d(3.2, 2.5, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Intake_4590_H_BUMP = new ChoreoTraj(
	    "H_Intake_4590_H_BUMP",
	    OptionalInt.empty(),
	    1.36677,
	    new Pose2d(7.4, 1.627, Rotation2d.fromRadians(0.785)),
	    new Pose2d(6.1, 2.5, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Intake_4590_H_BUMP$0 = new ChoreoTraj(
	    "H_Intake_4590_H_BUMP",
	    OptionalInt.of(0),
	    1.23191,
	    new Pose2d(7.4, 1.627, Rotation2d.fromRadians(0.785)),
	    new Pose2d(6.649, 2.5, Rotation2d.fromRadians(1.758))
	);
	public static final ChoreoTraj H_Intake_4590_H_BUMP$1 = new ChoreoTraj(
	    "H_Intake_4590_H_BUMP",
	    OptionalInt.of(1),
	    0.13485999999999998,
	    new Pose2d(6.649, 2.5, Rotation2d.fromRadians(1.758)),
	    new Pose2d(6.1, 2.5, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Intake_45_D_BUMP = new ChoreoTraj(
	    "H_Intake_45_D_BUMP",
	    OptionalInt.empty(),
	    2.01273,
	    new Pose2d(7.4, 1.627, Rotation2d.fromRadians(0.785)),
	    new Pose2d(6.1, 5.9, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj H_Intake_45_H_BUMP = new ChoreoTraj(
	    "H_Intake_45_H_BUMP",
	    OptionalInt.empty(),
	    1.42202,
	    new Pose2d(7.4, 1.627, Rotation2d.fromRadians(0.785)),
	    new Pose2d(6.1, 2.5, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Partial_1Pass = new ChoreoTraj(
	    "H_Partial_1Pass",
	    OptionalInt.empty(),
	    10.09805,
	    new Pose2d(3.439, 2.255, Rotation2d.fromRadians(0.785)),
	    new Pose2d(0.697, 0.657, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Partial_1Pass$0 = new ChoreoTraj(
	    "H_Partial_1Pass",
	    OptionalInt.of(0),
	    2.36631,
	    new Pose2d(3.439, 2.255, Rotation2d.fromRadians(0.785)),
	    new Pose2d(7.726, 0.582, Rotation2d.fromRadians(1.84))
	);
	public static final ChoreoTraj H_Partial_1Pass$1 = new ChoreoTraj(
	    "H_Partial_1Pass",
	    OptionalInt.of(1),
	    2.50506,
	    new Pose2d(7.726, 0.582, Rotation2d.fromRadians(1.84)),
	    new Pose2d(5.819, 2.452, Rotation2d.fromRadians(2.356))
	);
	public static final ChoreoTraj H_Partial_1Pass$2 = new ChoreoTraj(
	    "H_Partial_1Pass",
	    OptionalInt.of(2),
	    1.0647000000000002,
	    new Pose2d(5.819, 2.452, Rotation2d.fromRadians(2.356)),
	    new Pose2d(3.2, 2.452, Rotation2d.fromRadians(2.356))
	);
	public static final ChoreoTraj H_Partial_1Pass$3 = new ChoreoTraj(
	    "H_Partial_1Pass",
	    OptionalInt.of(3),
	    4.161980000000001,
	    new Pose2d(3.2, 2.452, Rotation2d.fromRadians(2.356)),
	    new Pose2d(0.697, 0.657, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Partial_1Pass_copy1 = new ChoreoTraj(
	    "H_Partial_1Pass_copy1",
	    OptionalInt.empty(),
	    7.56777,
	    new Pose2d(3.6, 2.05, Rotation2d.fromRadians(1.571)),
	    new Pose2d(1.596, 3.375, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj H_Partial_1Pass_copy1$0 = new ChoreoTraj(
	    "H_Partial_1Pass_copy1",
	    OptionalInt.of(0),
	    1.62406,
	    new Pose2d(3.6, 2.05, Rotation2d.fromRadians(1.571)),
	    new Pose2d(6.1, 2.05, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Partial_1Pass_copy1$1 = new ChoreoTraj(
	    "H_Partial_1Pass_copy1",
	    OptionalInt.of(1),
	    2.08644,
	    new Pose2d(6.1, 2.05, Rotation2d.fromRadians(1.571)),
	    new Pose2d(6.1, 2.7, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Partial_1Pass_copy1$2 = new ChoreoTraj(
	    "H_Partial_1Pass_copy1",
	    OptionalInt.of(2),
	    1.4518299999999997,
	    new Pose2d(6.1, 2.7, Rotation2d.fromRadians(1.571)),
	    new Pose2d(3.2, 2.7, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Partial_1Pass_copy1$3 = new ChoreoTraj(
	    "H_Partial_1Pass_copy1",
	    OptionalInt.of(3),
	    0.8790000000000004,
	    new Pose2d(3.2, 2.7, Rotation2d.fromRadians(1.571)),
	    new Pose2d(1.606, 0.674, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Partial_1Pass_copy1$4 = new ChoreoTraj(
	    "H_Partial_1Pass_copy1",
	    OptionalInt.of(4),
	    1.52644,
	    new Pose2d(1.606, 0.674, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.596, 3.375, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj H_Partial_2Pass = new ChoreoTraj(
	    "H_Partial_2Pass",
	    OptionalInt.empty(),
	    10.5572,
	    new Pose2d(3.513, 2.452, Rotation2d.fromRadians(0.785)),
	    new Pose2d(0.647, 0.557, Rotation2d.fromRadians(3.133))
	);
	public static final ChoreoTraj H_Partial_2Pass$0 = new ChoreoTraj(
	    "H_Partial_2Pass",
	    OptionalInt.of(0),
	    2.0277,
	    new Pose2d(3.513, 2.452, Rotation2d.fromRadians(0.785)),
	    new Pose2d(7.128, 0.794, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Partial_2Pass$1 = new ChoreoTraj(
	    "H_Partial_2Pass",
	    OptionalInt.of(1),
	    3.525,
	    new Pose2d(7.128, 0.794, Rotation2d.fromRadians(1.571)),
	    new Pose2d(5.819, 2.452, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj H_Partial_2Pass$2 = new ChoreoTraj(
	    "H_Partial_2Pass",
	    OptionalInt.of(2),
	    1.1175800000000002,
	    new Pose2d(5.819, 2.452, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(3.12, 2.466, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj H_Partial_2Pass$3 = new ChoreoTraj(
	    "H_Partial_2Pass",
	    OptionalInt.of(3),
	    0.39449999999999985,
	    new Pose2d(3.12, 2.466, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(2.772, 2.444, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj H_Partial_2Pass$4 = new ChoreoTraj(
	    "H_Partial_2Pass",
	    OptionalInt.of(4),
	    3.49242,
	    new Pose2d(2.772, 2.444, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(0.647, 0.557, Rotation2d.fromRadians(3.133))
	);
	public static final ChoreoTraj H_Partial_2Pass_Marked = new ChoreoTraj(
	    "H_Partial_2Pass_Marked",
	    OptionalInt.empty(),
	    10.61832,
	    new Pose2d(3.513, 2.452, Rotation2d.fromRadians(0.785)),
	    new Pose2d(0.647, 0.557, Rotation2d.fromRadians(-3.142))
	);
	public static final ChoreoTraj H_Partial_2Pass_Marked$0 = new ChoreoTraj(
	    "H_Partial_2Pass_Marked",
	    OptionalInt.of(0),
	    2.0277,
	    new Pose2d(3.513, 2.452, Rotation2d.fromRadians(0.785)),
	    new Pose2d(7.128, 0.794, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Partial_2Pass_Marked$1 = new ChoreoTraj(
	    "H_Partial_2Pass_Marked",
	    OptionalInt.of(1),
	    3.525,
	    new Pose2d(7.128, 0.794, Rotation2d.fromRadians(1.571)),
	    new Pose2d(5.819, 2.452, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj H_Partial_2Pass_Marked$2 = new ChoreoTraj(
	    "H_Partial_2Pass_Marked",
	    OptionalInt.of(2),
	    1.1175800000000002,
	    new Pose2d(5.819, 2.452, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(3.12, 2.466, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj H_Partial_2Pass_Marked$3 = new ChoreoTraj(
	    "H_Partial_2Pass_Marked",
	    OptionalInt.of(3),
	    0.3947599999999998,
	    new Pose2d(3.12, 2.466, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(2.772, 2.444, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj H_Partial_2Pass_Marked$4 = new ChoreoTraj(
	    "H_Partial_2Pass_Marked",
	    OptionalInt.of(4),
	    3.553280000000001,
	    new Pose2d(2.772, 2.444, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(0.647, 0.557, Rotation2d.fromRadians(-3.142))
	);
	public static final ChoreoTraj H_Partial_2Pass_NoShunt = new ChoreoTraj(
	    "H_Partial_2Pass_NoShunt",
	    OptionalInt.empty(),
	    8.59467,
	    new Pose2d(3.513, 2.452, Rotation2d.fromRadians(0.785)),
	    new Pose2d(1.779, 1.279, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Partial_2Pass_NoShunt$0 = new ChoreoTraj(
	    "H_Partial_2Pass_NoShunt",
	    OptionalInt.of(0),
	    2.0277,
	    new Pose2d(3.513, 2.452, Rotation2d.fromRadians(0.785)),
	    new Pose2d(7.128, 0.794, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Partial_2Pass_NoShunt$1 = new ChoreoTraj(
	    "H_Partial_2Pass_NoShunt",
	    OptionalInt.of(1),
	    3.525,
	    new Pose2d(7.128, 0.794, Rotation2d.fromRadians(1.571)),
	    new Pose2d(5.819, 2.452, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj H_Partial_2Pass_NoShunt$2 = new ChoreoTraj(
	    "H_Partial_2Pass_NoShunt",
	    OptionalInt.of(2),
	    1.1175800000000002,
	    new Pose2d(5.819, 2.452, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(3.12, 2.466, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj H_Partial_2Pass_NoShunt$3 = new ChoreoTraj(
	    "H_Partial_2Pass_NoShunt",
	    OptionalInt.of(3),
	    0.33528999999999964,
	    new Pose2d(3.12, 2.466, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(2.772, 2.444, Rotation2d.fromRadians(-2.356))
	);
	public static final ChoreoTraj H_Partial_2Pass_NoShunt$4 = new ChoreoTraj(
	    "H_Partial_2Pass_NoShunt",
	    OptionalInt.of(4),
	    1.589100000000001,
	    new Pose2d(2.772, 2.444, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(1.779, 1.279, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Shunt_Grab = new ChoreoTraj(
	    "H_Shunt_Grab",
	    OptionalInt.empty(),
	    10.22098,
	    new Pose2d(3.6, 2.1, Rotation2d.fromRadians(1.571)),
	    new Pose2d(0.693, 0.594, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Shunt_Grab$0 = new ChoreoTraj(
	    "H_Shunt_Grab",
	    OptionalInt.of(0),
	    1.75453,
	    new Pose2d(3.6, 2.1, Rotation2d.fromRadians(1.571)),
	    new Pose2d(6.136, 2.105, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Shunt_Grab$1 = new ChoreoTraj(
	    "H_Shunt_Grab",
	    OptionalInt.of(1),
	    2.67058,
	    new Pose2d(6.136, 2.105, Rotation2d.fromRadians(1.571)),
	    new Pose2d(8.263, 0.523, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Shunt_Grab$2 = new ChoreoTraj(
	    "H_Shunt_Grab",
	    OptionalInt.of(2),
	    0.8878399999999997,
	    new Pose2d(8.263, 0.523, Rotation2d.fromRadians(3.142)),
	    new Pose2d(5.756, 0.513, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Shunt_Grab$3 = new ChoreoTraj(
	    "H_Shunt_Grab",
	    OptionalInt.of(3),
	    1.1110800000000003,
	    new Pose2d(5.756, 0.513, Rotation2d.fromRadians(3.142)),
	    new Pose2d(5.789, 3.388, Rotation2d.fromRadians(1.559))
	);
	public static final ChoreoTraj H_Shunt_Grab$4 = new ChoreoTraj(
	    "H_Shunt_Grab",
	    OptionalInt.of(4),
	    1.6139799999999997,
	    new Pose2d(5.789, 3.388, Rotation2d.fromRadians(1.559)),
	    new Pose2d(3.2, 2.75, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Shunt_Grab$5 = new ChoreoTraj(
	    "H_Shunt_Grab",
	    OptionalInt.of(5),
	    2.182970000000001,
	    new Pose2d(3.2, 2.75, Rotation2d.fromRadians(1.571)),
	    new Pose2d(0.693, 0.594, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj H_Start_H_BUMP = new ChoreoTraj(
	    "H_Start_H_BUMP",
	    OptionalInt.empty(),
	    0.35524,
	    new Pose2d(3.6, 2.5, Rotation2d.fromRadians(1.571)),
	    new Pose2d(3.2, 2.5, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj H_Start_H_HumanPlayer = new ChoreoTraj(
	    "H_Start_H_HumanPlayer",
	    OptionalInt.empty(),
	    1.01098,
	    new Pose2d(3.6, 2.5, Rotation2d.fromRadians(1.571)),
	    new Pose2d(1.5, 0.65, Rotation2d.fromRadians(3.142))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("C_Climb", C_Climb),
		Map.entry("D_BumpAllianceNeutral", D_BumpAllianceNeutral),
		Map.entry("D_BumpNeutralAlliance", D_BumpNeutralAlliance),
		Map.entry("D_BUMP_D_Intake_45", D_BUMP_D_Intake_45),
		Map.entry("D_Depot_D_BUMP", D_Depot_D_BUMP),
		Map.entry("D_Full_1Pass", D_Full_1Pass),
		Map.entry("D_Full_1Pass$0", D_Full_1Pass$0),
		Map.entry("D_Full_1Pass$1", D_Full_1Pass$1),
		Map.entry("D_Full_1Pass$2", D_Full_1Pass$2),
		Map.entry("D_Full_1Pass$3", D_Full_1Pass$3),
		Map.entry("D_Full_1Pass$4", D_Full_1Pass$4),
		Map.entry("D_Intake_45_D_BUMP", D_Intake_45_D_BUMP),
		Map.entry("D_Intake_45_H_BUMP", D_Intake_45_H_BUMP),
		Map.entry("D_Partial_1Pass", D_Partial_1Pass),
		Map.entry("D_Partial_1Pass$0", D_Partial_1Pass$0),
		Map.entry("D_Partial_1Pass$1", D_Partial_1Pass$1),
		Map.entry("D_Partial_1Pass$2", D_Partial_1Pass$2),
		Map.entry("D_Partial_1Pass$3", D_Partial_1Pass$3),
		Map.entry("D_Partial_1Pass$4", D_Partial_1Pass$4),
		Map.entry("D_Start_D_BUMP", D_Start_D_BUMP),
		Map.entry("D_Start_D_Depot", D_Start_D_Depot),
		Map.entry("H_BumpNeutralAlliance", H_BumpNeutralAlliance),
		Map.entry("H_BUMP_H_Intake_45", H_BUMP_H_Intake_45),
		Map.entry("H_Full_1Pass", H_Full_1Pass),
		Map.entry("H_Full_1Pass$0", H_Full_1Pass$0),
		Map.entry("H_Full_1Pass$1", H_Full_1Pass$1),
		Map.entry("H_Full_1Pass$2", H_Full_1Pass$2),
		Map.entry("H_Full_1Pass$3", H_Full_1Pass$3),
		Map.entry("H_Full_1Pass$4", H_Full_1Pass$4),
		Map.entry("H_HumanPlayer_H_BUMP", H_HumanPlayer_H_BUMP),
		Map.entry("H_Intake_4590_H_BUMP", H_Intake_4590_H_BUMP),
		Map.entry("H_Intake_4590_H_BUMP$0", H_Intake_4590_H_BUMP$0),
		Map.entry("H_Intake_4590_H_BUMP$1", H_Intake_4590_H_BUMP$1),
		Map.entry("H_Intake_45_D_BUMP", H_Intake_45_D_BUMP),
		Map.entry("H_Intake_45_H_BUMP", H_Intake_45_H_BUMP),
		Map.entry("H_Partial_1Pass", H_Partial_1Pass),
		Map.entry("H_Partial_1Pass$0", H_Partial_1Pass$0),
		Map.entry("H_Partial_1Pass$1", H_Partial_1Pass$1),
		Map.entry("H_Partial_1Pass$2", H_Partial_1Pass$2),
		Map.entry("H_Partial_1Pass$3", H_Partial_1Pass$3),
		Map.entry("H_Partial_1Pass_copy1", H_Partial_1Pass_copy1),
		Map.entry("H_Partial_1Pass_copy1$0", H_Partial_1Pass_copy1$0),
		Map.entry("H_Partial_1Pass_copy1$1", H_Partial_1Pass_copy1$1),
		Map.entry("H_Partial_1Pass_copy1$2", H_Partial_1Pass_copy1$2),
		Map.entry("H_Partial_1Pass_copy1$3", H_Partial_1Pass_copy1$3),
		Map.entry("H_Partial_1Pass_copy1$4", H_Partial_1Pass_copy1$4),
		Map.entry("H_Partial_2Pass", H_Partial_2Pass),
		Map.entry("H_Partial_2Pass$0", H_Partial_2Pass$0),
		Map.entry("H_Partial_2Pass$1", H_Partial_2Pass$1),
		Map.entry("H_Partial_2Pass$2", H_Partial_2Pass$2),
		Map.entry("H_Partial_2Pass$3", H_Partial_2Pass$3),
		Map.entry("H_Partial_2Pass$4", H_Partial_2Pass$4),
		Map.entry("H_Partial_2Pass_Marked", H_Partial_2Pass_Marked),
		Map.entry("H_Partial_2Pass_Marked$0", H_Partial_2Pass_Marked$0),
		Map.entry("H_Partial_2Pass_Marked$1", H_Partial_2Pass_Marked$1),
		Map.entry("H_Partial_2Pass_Marked$2", H_Partial_2Pass_Marked$2),
		Map.entry("H_Partial_2Pass_Marked$3", H_Partial_2Pass_Marked$3),
		Map.entry("H_Partial_2Pass_Marked$4", H_Partial_2Pass_Marked$4),
		Map.entry("H_Partial_2Pass_NoShunt", H_Partial_2Pass_NoShunt),
		Map.entry("H_Partial_2Pass_NoShunt$0", H_Partial_2Pass_NoShunt$0),
		Map.entry("H_Partial_2Pass_NoShunt$1", H_Partial_2Pass_NoShunt$1),
		Map.entry("H_Partial_2Pass_NoShunt$2", H_Partial_2Pass_NoShunt$2),
		Map.entry("H_Partial_2Pass_NoShunt$3", H_Partial_2Pass_NoShunt$3),
		Map.entry("H_Partial_2Pass_NoShunt$4", H_Partial_2Pass_NoShunt$4),
		Map.entry("H_Shunt_Grab", H_Shunt_Grab),
		Map.entry("H_Shunt_Grab$0", H_Shunt_Grab$0),
		Map.entry("H_Shunt_Grab$1", H_Shunt_Grab$1),
		Map.entry("H_Shunt_Grab$2", H_Shunt_Grab$2),
		Map.entry("H_Shunt_Grab$3", H_Shunt_Grab$3),
		Map.entry("H_Shunt_Grab$4", H_Shunt_Grab$4),
		Map.entry("H_Shunt_Grab$5", H_Shunt_Grab$5),
		Map.entry("H_Start_H_BUMP", H_Start_H_BUMP),
		Map.entry("H_Start_H_HumanPlayer", H_Start_H_HumanPlayer)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
}
