package frc.robot.annotation;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedOptions;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;

@SupportedAnnotationTypes("frc.robot.annotation.AutoLogMavs")
@SupportedOptions("project.src.dir")
public class MavsAnnotationProcessor extends AbstractProcessor {

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {

    if (annotations.isEmpty()) {
      return false;
    }

    String srcDir = processingEnv.getOptions().get("project.src.dir");
    if (srcDir == null) {
      processingEnv
          .getMessager()
          .printMessage(Diagnostic.Kind.ERROR, "project.src.dir compiler option is not set");
      return true;
    }

    processingEnv
        .getMessager()
        .printMessage(Diagnostic.Kind.NOTE, "MavsAnnotationProcessor is running!");

    File outputDir = new File(srcDir, "frc/robot/annotation");
    outputDir.mkdirs();
    File outputFile = new File(outputDir, "AutoLogMAVSFINAL.java");

    String[] blockedAnnotations = new String[0];
    Set<? extends Element> disablers = roundEnv.getElementsAnnotatedWith(AutoLogDisabler.class);
    if (disablers.size() > 1) {
      processingEnv
          .getMessager()
          .printMessage(
              Diagnostic.Kind.ERROR,
              "There are more than one AutoLogDisabler annotations. Please remove the excess");
      return true;
    }
    for (Element e : disablers) {
      blockedAnnotations = e.getAnnotation(AutoLogDisabler.class).indexesToBlock();
    }

    try (FileWriter writer = new FileWriter(outputFile)) {
      writer.write("package frc.robot.annotation;\n\n");
      writer.write("import org.littletonrobotics.junction.Logger;\n\n");
      writer.write("import frc.robot.RobotContainer;\n\n");

      writer.write("public class AutoLogMAVSFINAL {\n");
      writer.write("  // Generated by MavsAnnotationProcessor\n");

      HashMap<String, String> items = new HashMap<>();

      for (Element i : roundEnv.getElementsAnnotatedWith(AutoLogMavsItem.class)) {
        items.put(i.asType().toString(), i.getSimpleName().toString());
      }
      writer.write("  @AutoLogDisabler(indexesToBlock = {");
      for (int i = 0; i < blockedAnnotations.length; i++) {
        if (i != blockedAnnotations.length - 1) {
          writer.write("\"" + blockedAnnotations[i] + "\", ");

        } else {
          writer.write("\"" + blockedAnnotations[i] + "\"");
        }
      }
      writer.write("})\n  public static void runMAVSLogging(RobotContainer robotContainer) {\n");
      for (Element i : roundEnv.getElementsAnnotatedWith(AutoLogMavs.class)) {
        if (i.getEnclosingElement().getSimpleName() != null) {
          String overClassName = i.getEnclosingElement().asType().toString();
          String actualName = items.get(overClassName);
          String simpleIndex = overClassName.substring(overClassName.lastIndexOf(".") + 1);
          String allIndex = simpleIndex + "/" + i.getAnnotation(AutoLogMavs.class).key();
          writer.write("    ");
          if (isBlocked(allIndex, blockedAnnotations)) {
            writer.write("// BLOCKED AUTOMATICALLY  ");
          }
          writer.write(
              "Logger.recordOutput(\""
                  + allIndex
                  + "\", robotContainer."
                  + actualName
                  + "."
                  + i.getSimpleName()
                  + (i.getKind() == ElementKind.METHOD ? "()" : "")
                  + ");\n");
        }
      }
      writer.write("  }\n");

      writer.write("}\n");
    } catch (IOException e) {
      processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, e.toString());
    }
    return true;
  }

  /**
   * A key is blocked if a blocked entry matches it exactly, or if the entry is a parent path of it
   * (e.g. "Drive" blocks "Drive/Pose" and "Drive/Module/Speed", but not "Drivetrain/Pose").
   */
  private static boolean isBlocked(String key, String[] blockedKeys) {
    for (String blocked : blockedKeys) {
      if (blocked.equals("/")) {
        return true;
      }
      String prefix = blocked.endsWith("/") ? blocked.substring(0, blocked.length() - 1) : blocked;
      if (prefix.isEmpty()) {
        continue;
      }
      if (key.equals(prefix) || key.startsWith(prefix + "/")) {
        return true;
      }
    }
    return false;
  }
}
