package frc.robot.annotation;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedOptions;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;

@SupportedAnnotationTypes("frc.robot.annotation.AutoLogMavs")
@SupportedOptions("project.src.dir")
public class MavsAnnotationProcessor extends AbstractProcessor {

  @Override
  public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {

    if (annotations.isEmpty()) {
      return false;
    }

    String srcDir = processingEnv.getOptions().get("project.src.dir");
    if (srcDir == null) {
      processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
          "project.src.dir compiler option is not set");
      return true;
    }

    processingEnv
        .getMessager()
        .printMessage(Diagnostic.Kind.NOTE, "MavsAnnotationProcessor is running!");

    File outputDir = new File(srcDir, "frc/robot/annotation");
    outputDir.mkdirs();
    File outputFile = new File(outputDir, "AutoLogMAVSFINAL.java");

    try (FileWriter writer = new FileWriter(outputFile)) {
      writer.write("package frc.robot.annotation;\n\n");
      writer.write("public class AutoLogMAVSFINAL {\n");
      writer.write("  // Generated by MavsAnnotationProcessor\n");
      writer.write("}\n");
    } catch (IOException e) {
      processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, e.toString());
    }
    return true;
  }
}
